spring:
  application:
    name: movie-migration-service
  flyway:
    user: postgres
    password: password
    schemas: migrationScheme

springdoc:
  swagger-ui:
    path: /swagger-ui.html

#TODO: add flyway config, postgres config, add swagger config(added)