spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    url:
    user:
    password:
    baseline-on-migrate: false
    locations: classpath:db/migration
    schemas: public



springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs