spring:
  application:
    name: movie-migration-service
  flyway:
    baseline-on-migrate: true
  datasource:
    username: postgres
    password: parola
    url: jdbc:postgresql://localhost:5432/migrations

springdoc:
  swagger-ui:
    path: /swagger-ui.html

#TODO: add flyway config, postgres config, add swagger config(added)