spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/migrations
    username: cezar
    password: parola

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs


#spring.datasource.username=cezar
#spring.datasource.password=parola
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/api-docs
